services:
  # Elasticsearch service
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: onebox-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - onebox-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s



  # OneBox API service
  onebox-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: onebox-api
    environment:
      - NODE_ENV=production
      - PORT=5001
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=password
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/email_onebox?schema=public
      - CLIENT_URL=${CLIENT_URL:-http://localhost:8080}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    ports:
      - "5001:5001"
    depends_on:
      elasticsearch:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - onebox-network
    volumes:
      - ./credentials.json:/app/credentials.json:ro
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5001/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # PostgreSQL service
  postgres:
    image: postgres:16-alpine
    container_name: onebox-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=email_onebox
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - onebox-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d email_onebox"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  # Optional: Kibana for Elasticsearch management
  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.0
    container_name: onebox-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - xpack.security.enabled=false
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - onebox-network
    profiles:
      - monitoring

volumes:
  elasticsearch_data:
    driver: local
  postgres_data:
    driver: local

networks:
  onebox-network:
    driver: bridge
